import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.scss";
import AppInitializer from "@/components/AppInitializer";
import ThemeSwitcher from "@/components/ThemeSwitcher";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My SCSS Themed App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppInitializer>
          <ThemeSwitcher />
          {children}
        </AppInitializer>
      </body>
    </html>
  );
}
